config/routes.rb
Rails.application.routes.draw do
  root to: "examples#index"

  get "/console", to: "examples#console"
  get "/clipboard", to: "examples#clipboard"
  get "/isp_form", to: "examples#isp_form"
  get "/action_arguments", to: "examples#action_arguments"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/forms_helper.rb
module FormsHelper
	def states_for_select
		%w[
			AK
			CA
			KY
			TX
		]
	end
end

app/views/examples/action_arguments.html.erb
<h1>Passing Arguments To Actions</h1>

<div data-controller="action-arguments">
	<div data-action="skip"	data-argument="0">Write Argument To Console</div>
</div>

app/views/examples/clipboard.html.erb
<h2>Copy From Text Field</h2>

<div data-controller="clipboard">
	<input data-target="clipboard.source" type="text" value="http://www.example.com/somethingcool" readonly>

	<%= button_tag :copy, data: { action: "clipboard#copy" } %>
</div>

app/views/examples/console.html.erb
<div data-controller="foo">
  <h1>Console Example</h1>

  <%= text_field_tag :name, "name", data: { target: "foo.name" } %>
  <%= button_tag :submit, data: { action: "foo#greet" } %>
</div>

app/views/examples/index.html.erb
<h1>Stimulus.js Rails Examples</h1>

<%= link_to "Web Console", console_path %> 
<br>
<%= link_to "Clipboard", clipboard_path %> 
<br>
<%= link_to "ISP Form", isp_form_path %> 
<br>
<%= link_to "Passing Arguments To Actions", action_arguments_path %> 

app/views/examples/isp_form.html.erb
<%= image_tag("pai-santa-clown.jpg") %>
<h1>"Of Course ISPs have a healthy amount of competition."</h1>


<div data-controller="isp">
  <h3>Select Your State Below:</h3>
  <%= select "state", 
    "abbrev_state", 
    options_for_select(states_for_select), 
    { include_blank: true }, 
    { data: 
      { 
        target: "isp.state", 
        action: "isp#render"
      } 
    } %>

  <div data-target="isp.at-t">AT&amp;T</div>
  <div data-target="isp.comcast">Comcast</div>
  <div data-target="isp.twc">Time Warner</div>
  <div data-target="isp.xfinity">Xfinity</div>
  <div data-target="isp.spectrum">Spectrum</div>
</div>

app/views/forms/index.html.erb
<%= image_tag("pai-santa-clown.jpg") %>
<h1>"Of Course ISPs have a healthy amount of competition."</h1>


<div data-controller="isp">
	<h3>Select Your State Below:</h3>
	<%= select "state", 
		"abbrev_state", 
		options_for_select(states_for_select), 
		{ include_blank: true }, 
		{ data: 
			{ 
				target: "isp.state", 
				action: "isp#render"
			} 
		} %>

	<div data-target="isp.at-t">AT&amp;T</div>
	<div data-target="isp.comcast">Comcast</div>
	<div data-target="isp.twc">Time Warner</div>
	<div data-target="isp.xfinity">Xfinity</div>
	<div data-target="isp.spectrum">Spectrum</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div data-controller="foo">
  <h1>Console Example</h1>

  <%= text_field_tag :name, "name", data: { target: "foo.name" } %>
  <%= button_tag :submit, data: { action: "foo#greet" } %>
</div>

<br>

<%= link_to 'ISP Form Example', forms_path %>

<br>

<%= link_to 'Clipboard Example', clipboard_path %>